defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: best
  monitor: "train/loss"
  verbose: false
  save_last: false
  save_top_k: 1
  mode: "min"

early_stopping:
  monitor: "train/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
